### ISSUE TITLE
Add "when to cite what" guide

### ISSUE THREAD

**Issue by uekerman** [precice/precice.github.io#177]
Now that the new reference paper is accepted, which should update our citation guidelines.
When to cite:
- the new ref paper
- the old ref paper
- the distribution
- adapter papers

We could describe this in detail in one place and link to it from the landing page, the precice/precice README, the literature guide, ...
Where could this one place be? 
- https://precice.org/publications.html#how-to-cite-precice or
- a new section on https://precice.org/fundamentals-literature-guide.html
- or a separate new side under "community"

Opinions, ideas?

**Comment by MakisH** [comment]
> We could describe this in detail in one place and link to it from the landing page, the precice/precice README, the literature guide, ... Where could this one place be?
> 
>     * https://precice.org/publications.html#how-to-cite-precice or
> 
>     * a new section on https://precice.org/fundamentals-literature-guide.html
> 
>     * or a separate new side under "community"
> 
> 
> Opinions, ideas?

We already link to the "Literature guide" from the homepage, which comes early in the documentation. I think this should be the main place to find how to cite preCICE. Ideally, I could imagine "tabs" in the home page: the first tab is called "cite preCICE" and points to the v2 paper and the second tab is called something like "cite data" (yes, I know, not ideal name). We could potentially have a third tab "cite adapters".

To me, it feels natural to add a new section "Key references" there, since these are the main articles one should read (mainly the v2 and v1 papers).

This does already compete, however, with the statement at the [Publications page](https://precice.org/publications.html) "how to cite preCICE?". We also have the distribution in a separate page (under "Installation"), which also provides citable DOIs.

I would not add another page, especially since we already have some fragmentation on this. And, if any, I see it as a better fit for the "Docs", than for "Community", since it is a fundamental aspect of the software, not something that derives of / mainly concerns the community.
