### ISSUE TITLE
Add form for testimonials

### ISSUE THREAD

**Issue by uekerman** [precice/precice.github.io#33]
On the testimonials page, there is currently a button `Tell us your story`, which leads to `resources/#contact`. 

I would be better if the link leads to a form where people can submit their testimonial. This could be a simple google form or something similar, let's not reinvent the wheel. Nice side-effect would be that we than could also give this link to whomever we want to ask for a testimonial. Currently, I always copy-paste the required information into a mail. 

**What we would need:** 

Title (ideally related to your application/ your research, not the coupled codes etc.)

Text (max characters including spaces 800)
 * Which application?
 * Which solvers have you coupled?
 * Why have you used preCICE?

Name,
Affiliation,
Link to personal web page (optional),
Link to publication (optional)

Picture (ideally high resolution)

**Comment by MakisH** [comment]
I am not sure if a form is still relevant. We could ask them to directly add a file in https://github.com/precice/precice.github.io/tree/master/collections/_testimonials as a pull request.

**Comment by BenjaminRodenberg** [comment]
I like the idea of using a pull request here. If we want to give some more guidance, we can provide an empty testimonial file as a template that users just copy and fill out.

If we create a form we have to develop & maintain it. I don't see real benefits over using the github-based workflow, since we can assume that our users have a github account and know how to create a PR; if (hopefully few) users don't meet these requirements, we can still offer to get in contact with us via mail.

**Comment by uekerman** [comment]
Agree. We should still update the text there though. The "tell us your story" has not yet worked a single time :grin:

**Comment by MakisH** [comment]
Related to #283.
