### ISSUE TITLE
Duplication of publication information

### ISSUE THREAD

**Issue by ajaust** [precice/precice.github.io#98]
Currently, the homepage tends to duplicate literature information, especially for the (current) preCICE reference paper from 2016. This could be the case for other publications as well.

Information about the reference paper is encoded (at least) in:
- `collections/_publications/2016-BungartzLindnerGatzhammerMehlScheufeleShukaevUekermann.md`: In general `collections/_publications` collects all information about publications in markdown files with a YAML header.
- `pages/index.html`: This file contains a [hard coded code block](https://github.com/precice/precice.github.io/blob/ca305cd3581071c39a1a954f27d78481db98ffaa/pages/index.html#L309) with the paper information.
- `pages/community/publications.md`: This file generates a literature overview automatically from all literature in `collections/_publications`. However, the preCICE reference paper is [a hard coded block](https://github.com/precice/precice.github.io/blob/ca305cd3581071c39a1a954f27d78481db98ffaa/pages/community/publications.md?plain=1#L15) again.

I would suggest avoiding duplication of information that might go out of date. You already have the ability to autogenerate literature entries. I am currently implement something like that for the FEniCS-preCICE paper, see #97.

This would need:
- Enough metadata in the publication entries
- Publication dependent formatting of the entries. See #97, for example, where the reference paper and the Bachelor's thesis are formatted differently (I do not claim that the formatting is perfect yet).

**Comment by MakisH** [comment]
I think we have improved the situation a lot here, and since #201:

- `collections/_publications` is not rendered anywhere anymore as a full list. We could eventually remove the metadata files as well, but I don't see the reason to do that yet (we may want to refer to some of these in different places later).
- `pages/index.html` is still hard-coded, but I don't think we can/should change something there
- `pages/community/publications.md` does not exist anymore and redirects to the [literature guide](https://precice.org/fundamentals-literature-guide.html).
- The literature guide does use the database now, based on how you did it for the FEniCS-preCICE adapter paper.

Note that adapters still use hard-coded entries. Maybe we should keep the issue open till we also migrate those pages as well.

**Comment by MakisH** [comment]
> Note that adapters still use hard-coded entries. Maybe we should keep the issue open till we also migrate those pages as well.

Actually, since the content for the adapters is (or will be) fetched from external repositories, replacing the hard-coded references with pointers to this publications database will destroy the in-repository documentation. Let's not invest further into this. There are already links to the related resources.
